dist: trusty
sudo: required
language: web

addons:
  sonarcloud:
    # info obtenue sur https://sonarcloud.io/account/security
    organization: "fbab-github"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - sonar-scanner -X
